### ISSUE TITLE
BE able to monitor website, ping ip address, process running and if stops, resets the pc

### ISSUE THREAD

**Issue by leopucci** [rbicelli/usb-watchdog-control#1]
Hi, i am testing to see if it works with my usb watchdog. 
some things that i would like is to be able to monitor the aplication responding and take action 
like ip addresses pinging, 
process runing on the system
things like that

**Comment by rbicelli** [comment]
Hello,
what are you asking is outside of scope of the application. The application is intended to do a single thing: sending heartbeat to USB device. If you are looking for ping probes, website probes, process probes you should look at Zabbix, Icinga, Nagios or monitoring software in general.

**Comment by leopucci** [comment]
![image](https://user-images.githubusercontent.com/38509299/232789240-b4d529c0-ff9c-4750-a8fb-45bd36a3f2f5.png)
this is the software that came with the watchdog these days. 
I am looking for a open source version that could do the same
For me the reset based on application response makes sense and is more valuable than a graphana notification

**Comment by rbicelli** [comment]
Sorry but that software is the reason that  motivated me to write this watchdog.
Hopefully, if a program is not responding, you could try a graceful shutdown. In a graceful shutdown scenario the wachdog heartbeat is suspended and if the shutdown takes longer the hardware would do its job: trigger the reset button.
If you need to monitor a website or a specific application i suggest to write a script that does what you need and if conditions are not met:

- closes the watchdog program (taskkill /IM ... /F)
- trigger a reboot

Or if you have time to invest sources are available ;-)
